### ISSUE TITLE
First Practice Web Page

### ISSUE THREAD

**Issue by itsevan** [slins1/cs-club-website#2]
Here's a practice page to try and copy from that I cooked up for ya.

![firstsite](https://cloud.githubusercontent.com/assets/8126513/13236360/d0e26350-d991-11e5-8ef9-1383d176c07a.png)

Shouldn't be too hard. If it's too easy, try making it responsive, or making a drop-down menu.

**Comment by itsevan** [comment]
Here is my draft code, feel free to look at it and ask questions if you need help.

https://github.com/itsevan/practicedev

You can download the zip and view from your own computer.

**Comment by slins1** [comment]
This looks great. How'd you come up with the CSS if you don't mind my asking?

**Comment by itsevan** [comment]
The responsive design/media queries I got from W3Schools:

 http://www.w3schools.com/css/css_rwd_mediaqueries.asp

I used flex boxes to vertically align certain elements such as the body and the picture

http://www.w3schools.com/css/css3_flexbox.asp

All values attributed to height and width are in either em or %; making it scalable for mobile

Color values are in HSL format, as to allow for browser compatibility and its easier IMO to edit the output as opposed to RGB.

**Comment by patrickfero** [comment]
I enjoy the DJ Khaled references

**Comment by itsevan** [comment]
http://khaledipsum.com/

**Comment by itsevan** [comment]
If you worked on this assignment, post the code now so we can talk about it on Monday.
